# Generated by Django 4.1 on 2022-08-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
